category_examples = {
    "Computer Science": [
        "Efficient Transformer Architectures for Large-Scale Language Models",
        "Training Large Language Models with Sparse Attention",
        "Real-Time Object Detection Using Convolutional Neural Networks",
        "Autonomous Navigation with Reinforcement Learning in Dynamic Environments",
        "Self-Supervised Learning for Multimodal Representations",
        "Prompt Engineering Strategies for Zero-Shot Learning with LLMs",
        "Differential Privacy in Federated Learning Systems",
        "Scalable Graph Neural Networks for Social Network Analysis",
        "Explainable AI Techniques in Decision-Making Systems",
        "Fine-Tuning Language Models for Interactive AI Agents",
    ],
    "Biology": [
        "CRISPR-Cas9 Mediated Gene Editing in Human Stem Cells",
        "Gene Expression Mapping in Fruit Flies",
        "Adaptive Immunity in Marine Organisms",
        "Single-Cell RNA Sequencing for Tissue Development Analysis",
        "Microbiome Influence on Human Metabolic Health",
        "Epigenetic Regulation in Cancer Cell Proliferation",
        "Genomic Adaptations in High-Altitude Mammals",
        "Protein Folding Prediction Using AlphaFold",
        "Circadian Rhythm Disruption in Aging Populations",
        "Cell Signaling Pathways in Immune Response Modulation",
        "Synthetic Biology Approaches for Biodegradable Plastics",
        "Metagenomics for Biodiversity Assessment in Ecosystems",
        "Neurogenetics of Behavior in Model Organisms",
        "Biophysical Techniques for Protein-Protein Interaction Studies",
        "Plant-Microbe Interactions in Soil Health",
        "Bioinformatics Tools for Genome-Wide Association Studies",
        "Systems Biology Approaches to Metabolic Engineering",
    ],
    "Engineering": [
        "Optimizing Structural Design with Topology-Based AI Models",
        "Robotics in Autonomous Vehicle Navigation",
        "Designing Resilient Infrastructure for Earthquake Zones",
        "Thermal Optimization in Sustainable Building Materials",
        "Control Systems for Smart Grid Energy Management",
        "Additive Manufacturing of Aerospace Components",
        "Mechanical Fatigue Analysis in Offshore Wind Turbines",
        "Swarm Robotics for Search and Rescue Missions",
        "Wireless Sensor Networks in Industrial Automation",
        "Cyber-Physical Systems Security in IoT Applications",
    ],
    "Physics": [
        "Quantum Entanglement and Decoherence in Superconducting Qubits",
        "Gravitational Waves from Binary Black Hole Mergers",
        "The Higgs Boson Discovery and Its Implications",
        "Topological Insulators and Quantum Transport Phenomena",
        "Laser Cooling and Trapping of Neutral Atoms",
        "Dark Matter Detection Using Cryogenic Detectors",
        "Magnetohydrodynamics in Astrophysical Plasmas",
        "Neutrino Oscillation Experiments and Beyond the Standard Model",
        "Chaos Theory and Nonlinear Dynamics in Physical Systems",
        "Superfluidity and Bose-Einstein Condensates in Ultracold Gases",
        "Nanophotonics and Plasmonic Metamaterials for Light Manipulation",
        "Quantum Computing Algorithms for Solving NP-Complete Problems",
        "Experimental Techniques in High-Energy Particle Physics",
        "Astrobiology and the Search for Extraterrestrial Life",
        "Thermodynamics of Black Holes and Information Paradox",
        "Quantum Gravity Theories and Their Implications",
        "Experimental Validation of Quantum Field Theories",
        "Cosmological Inflation and the Early Universe",
    ],
    "Chemistry": [
        "Catalytic Pathways for CO2 Reduction Using Metal-Organic Frameworks",
        "Synthesis of Novel Organic Semiconductors for Solar Cells",
        "Kinetics of Enzyme-Catalyzed Reactions in Aqueous Environments",
        "Molecular Dynamics of Hydrogen Bond Networks in Water",
        "Green Chemistry Approaches for Pharmaceutical Synthesis",
        "Electrochemical Properties of Redox-Active Polymers",
        "Supramolecular Chemistry and Host-Guest Interactions",
        "Photocatalysis for Water Splitting Applications",
        "Metal-Ligand Coordination Complexes in Drug Design",
        "Spectroscopic Analysis of Atmospheric Pollutants",
        "Nanomaterials for Drug Delivery Systems",
        "Computational Chemistry in Predicting Reaction Mechanisms",
        "Chemical Sensors for Environmental Monitoring",
        "Biomimetic Catalysis Inspired by Nature",
        "Polymer Chemistry for Advanced Material Applications",
    ],
    "Public Policy": [
        "Analyzing the Impact of Federal Incentives on Renewable Energy Adoption",
        "Policy Approaches to Reducing Urban Homelessness",
        "The Role of Regulation in Advancing Clean Transportation",
        "Evaluating the Effects of Universal Basic Income Trials",
        "Healthcare Access Policy and Equity in Rural Populations",
        "Privacy Legislation in the Age of Big Data",
        "Education Policy Reform and Charter School Outcomes",
        "Immigration Policy and Economic Integration of Refugees",
        "Criminal Justice Reform and Recidivism Rates",
        "Climate Policy Innovation in Subnational Governments",
        "Public Health Policy Responses to Pandemics",
        "The Role of Nonprofits in Addressing Food Insecurity",
        "Urban Planning and Zoning Laws for Affordable Housing",
        "Cybersecurity Policy in Critical Infrastructure Protection",
        "International Trade Policy and Tariff Impacts",
        "Public Policy Approaches to Addressing Income Inequality",
        "Disaster Resilience Policy in Coastal Communities",
        "The Role of Public-Private Partnerships in Infrastructure Development",
    ],
    "Economics": [
        "Behavioral Responses to Inflation Shocks in Consumer Markets",
        "Game Theory and Strategic Interactions in Auctions",
        "Income Inequality and Tax Policy Reform in OECD Countries",
        "Labor Market Effects of Automation and AI Technologies",
        "Cryptocurrency Volatility and Its Macroeconomic Implications",
        "Pricing Strategies in Platform-Based Gig Economies",
        "The Economics of Climate Change Adaptation Strategies",
        "Housing Market Dynamics and Urban Gentrification",
        "Financial Inclusion and Microcredit in Emerging Economies",
        "Global Trade Shocks and Supply Chain Resilience",
        "The Role of Central Banks in Financial Stability",
        "Public Goods Provision and Collective Action Problems",
        "Economic Impacts of COVID-19 on Small Businesses",
        "Monetary Policy Transmission Mechanisms in Emerging Markets",
        "The Economics of Renewable Energy Subsidies",
        "Labor Economics and Wage Determination Models",
    ]
}